### ISSUE TITLE
How to do ROI pooling when using average support feature？

### ISSUE THREAD

**Issue by 978326187** [fanq15/Few-Shot-Object-Detection-Dataset#15]
You say ‘The proposal box of the support sample is from the GT label. Because we are given the support image and boxes to detect objects in the query images.’
In Fig 4 you mention that For N-shot training, we obtain all the support feature through the weight-shared network and use the average feature across all the supports belonging to the same category as its support feature.
But how can we use GT label in average feature？

**Comment by fanq15** [comment]
Support images have ground truth boxes, and we use it to RoI Pooling features in the boxes. And every box has its category label, we use the category label to gather supports and then we average the features belonging to the same support category as the support feature.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 978326187 <notifications@github.com>
发送时间: Sunday, April 5, 2020 1:57:11 PM
收件人: fanq15/Few-Shot-Object-Detection-Dataset <Few-Shot-Object-Detection-Dataset@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [fanq15/Few-Shot-Object-Detection-Dataset] How to do ROI pooling when using average support feature？ (#15)


You say ‘The proposal box of the support sample is from the GT label. Because we are given the support image and boxes to detect objects in the query images.’
In Fig 4 you mention that For N-shot training, we obtain all the support feature through the weight-shared network and use the average feature across all the supports belonging to the same category as its support feature.
But how can we use GT label in average feature？

―

**Comment by 978326187** [comment]
So，the average support feature just used in attention RPN（Fig 5）？
