### ISSUE TITLE
Details of training Attention-RPN & Multi-R Detector

### ISSUE THREAD

**Issue by XiongweiWu** [fanq15/Few-Shot-Object-Detection-Dataset#6]
Hi, what's the batch size when training your proposed detector  ? Your default setting is 2-way-5-shot, so the input should be  (5 support images + 1 query images + 5 negative support images) * 2. on each GPU card (the memory seems be an issue)? And the total iterations are 22*60k? I am trying to reimplement your work and try to query the details of your training settings. Can u show me ur details of training? Thx

**Comment by fanq15** [comment]
One GPU contains only 1 query image and 5*2 support images. I use 4GPUs, so the batch size is 4 for the query image. The total iteration for this setting is 60000 iterations. This setting only takes about 4GB on each GPU.

**Comment by XiongweiWu** [comment]
@fanq15 So for each card, 1 query image (600x1000) + 5 support images (320x320) + 5 negative support images (320x320) are fed into the network. Totally 11*4 images  (4 cards) are trained for 60k. Is the category of query image randomly selected on each card?

**Comment by fanq15** [comment]
Yes, it is exactly what you said. Both the query and support images are randomly selected for each card.  The code is expected to be released in two months. Because I need to clean the code and I want to transfer it to the newest detectron2 framework (The original version is on an unofficial framework `detectron-tw`). I hope I can finish it this month.
